version: '3.1'

services:

  api:
    build: server-example
    volumes:
      - ./server-example:/home/node
      - ./gongo-server:/home/node/node_modules/gongo-server
    depends_on:
      - mongo

  mongo:
    image: mongo:4
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
