version: '3.1'

services:

  mongo1:
    image: mongo:4
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo2:
    image: mongo:4
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo3:
    image: mongo:4
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongosetup:
    image: mongo:4
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "bash", "/scripts/mongosetup.sh" ]
    depends_on:
      - mongo1
      - mongo2
      - mongo3
